return {
  -- "vague-theme/vague.nvim",
  -- lazy = false,
  -- priority = 1000,
  -- config = function()
  --   require("vague").setup({
  --     transparent = false,
  --     bold = false,
  --     italic = false,
  --     colors = {
  --       -- Core
  --       bg = "#1c1c1c",
  --       fg = "#cccccc",
  --       inactiveBg = "#262626",
  --       line = "#262626",
  --       visual = "#262626",
  --       search = "#262626",
  --       floatBorder = "#ffd700",
  --       -- Syntax
  --       comment = "#af875f",
  --       string = "#87d75f",
  --       func = "#87afd7",
  --       keyword = "#ffd700",
  --       type = "#cccccc",
  --       constant = "#afd7af",
  --       number = "#afd7af",
  --       builtin = "#afd7af",
  --       parameter = "#cccccc",
  --       property = "#cccccc",
  --       operator = "#cccccc",
  --       -- Diagnostics
  --       error = "#ff5f5f",
  --       warning = "#ffd700",
  --       hint = "#87afd7",
  --       -- Diff
  --       plus = "#87d75f",
  --       delta = "#87afd7",
  --     },
  --   })
  --   vim.cmd("colorscheme vague")
  -- end,
}
